### ISSUE TITLE
Align data folder names aligned with the next release of migration tools

### ISSUE THREAD

**Issue by branchedelac** [FOLIO-FSE/migration_repo_template#1]
When releasing [the new version of the migration tools](https://github.com/FOLIO-FSE/MARC21-To-FOLIO/milestones), change the names of the data folders to match what the migration tools expect.

instance > instances
holdingsrecord > holdings
item > items

**Comment by fontanka16** [comment]
I believe this has been done! Right, @branchedelac ?
