### ISSUE TITLE
SSL error when running folio_migration_tools

### ISSUE THREAD

**Issue by shreo1992-beep** [FOLIO-FSE/migration_repo_template#4]
when i run the following python -m folio_migration_tools --okapi_password mpl_admin@123 --base_folder_path D:\MPL_Migration_Tool\migration_repo_template-main D:\MPL_Migration_Tool\migration_repo_template-main\mapping_files\Configuration.json transform_bibs to create instance it gives me the following error SSL error. Are you connected to the Internet and the VPN? all my tenant info is located in Configuration.json my okapi url is https://okapi.medad.com i have checked if my server is connected to vpn or not and there is no vpn being used i have made sort of get request on the okapi url and it is working so can you help me to solve this issue

**Comment by fontanka16** [comment]
Sorry for the late reply. It is very weird.  Looking at that URL, it seems like a valid OKAPI Url.  if you just to a cURL or wget from the same machine, does return a proper response? @shreo1992-beep

**Comment by bltravis** [comment]
This would be a `folio_migration_tools` issue, not a problem with the template.
